from enum import Enum


class SignalType(str, Enum):
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


class OrderSide(str, Enum):
    BUY = "BUY"
    SELL = "SELL"


class OrderType(str, Enum):
    MARKET = "MARKET"
    LIMIT = "LIMIT"


class OrderStatus(str, Enum):
    PENDING = "PENDING"
    VALIDATED = "VALIDATED"
    SIZED = "SIZED"
    PENDING_APPROVAL = "PENDING_APPROVAL"  # Human-in-the-loop
    SUBMITTED = "SUBMITTED"
    SUBMITTING = "SUBMITTING"  # Persisted before sending to exchange
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"


class PositionSide(str, Enum):
    LONG = "LONG"  # Solo LONG para spot


class PositionStatus(str, Enum):
    OPEN = "OPEN"
    PARTIALLY_CLOSED = "PARTIALLY_CLOSED"
    CLOSED = "CLOSED"
    STOPPED_OUT = "STOPPED_OUT"


class ExecutionMode(str, Enum):
    PAPER = "PAPER"
    LIVE = "LIVE"


class RiskAction(str, Enum):
    APPROVE = "APPROVE"
    REJECT = "REJECT"
    REDUCE_SIZE = "REDUCE_SIZE"
    HALT_SYSTEM = "HALT_SYSTEM"


class EventType(str, Enum):
    # Signal events
    SIGNAL_GENERATED = "SIGNAL_GENERATED"
    SIGNAL_EXPIRED = "SIGNAL_EXPIRED"

    # Risk events
    RISK_APPROVED = "RISK_APPROVED"
    RISK_REJECTED = "RISK_REJECTED"

    # Guard events
    GUARD_APPROVED = "GUARD_APPROVED"
    GUARD_REJECTED = "GUARD_REJECTED"

    # Order events
    ORDER_CREATED = "ORDER_CREATED"
    ORDER_SIZED = "ORDER_SIZED"
    ORDER_SUBMITTED = "ORDER_SUBMITTED"
    ORDER_FILLED = "ORDER_FILLED"
    ORDER_PARTIALLY_FILLED = "ORDER_PARTIALLY_FILLED"
    ORDER_CANCELLED = "ORDER_CANCELLED"
    ORDER_EXPIRED = "ORDER_EXPIRED"

    # Position events
    POSITION_OPENED = "POSITION_OPENED"
    POSITION_PARTIALLY_CLOSED = "POSITION_PARTIALLY_CLOSED"
    POSITION_CLOSED = "POSITION_CLOSED"
    STOP_LOSS_TRIGGERED = "STOP_LOSS_TRIGGERED"
    TAKE_PROFIT_TRIGGERED = "TAKE_PROFIT_TRIGGERED"
    STOP_LOSS_UPDATED = "STOP_LOSS_UPDATED"

    # System events
    CIRCUIT_BREAKER_ACTIVATED = "CIRCUIT_BREAKER_ACTIVATED"
    CIRCUIT_BREAKER_RESET = "CIRCUIT_BREAKER_RESET"
    SYSTEM_HALTED = "SYSTEM_HALTED"
    SYSTEM_RESUMED = "SYSTEM_RESUMED"
    DAILY_LOSS_LIMIT_REACHED = "DAILY_LOSS_LIMIT_REACHED"
    STRATEGY_DEACTIVATED = "STRATEGY_DEACTIVATED"


class AggregateType(str, Enum):
    SIGNAL = "SIGNAL"
    ORDER = "ORDER"
    POSITION = "POSITION"
    SYSTEM = "SYSTEM"
    STRATEGY = "STRATEGY"
